######### 锚点 start #######
#这里是订阅更新和延迟测试相关的
p: &p {type: http}

use: &use
  type: select
  use:
  - provider1
  - provider2

######### 锚点 end #######


# url 里填写自己的订阅,名称不能重复
proxy-providers:
  provider1:
    <<: *p
    url: ""
    path: ./provider1.yaml

  provider2:
    <<: *p
    url: ""
    path: ./provider2.yaml

ipv6: false
mode: rule
log-level: info
allow-lan: true
mixed-port: 7890
external-controller: 127.0.0.1:9090

geodata-mode: true
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"


unified-delay: false
tcp-concurrent: true
find-process-mode: strict
global-client-fingerprint: chrome
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - 'tls://1.0.0.1#默认'
    - 'tls://8.8.4.4#默认'
    # - 223.5.5.5
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - 223.5.5.5
      - 223.6.6.6

proxy-groups:

  - {name: 默认, type: select, proxies: [全部节点, 香港, 新加坡, 台湾, 日本, 美国, 其它地区, 自动选择, DIRECT]}

  - {name: 香港, <<: *use,filter: "(?i)港|hk|hongkong|hong kong", type: select}

  - {name: 新加坡, <<: *use, filter: "(?i)(新|sg|singapore)", type: select}

  - {name: 日本, <<: *use, filter: "(?i)日本|jp|japan", type: select}

  - {name: 全部节点, <<: *use, type: select}
  
  - {name: 台湾, <<: *use, filter: "(?i)台|tw|taiwan", type: select}

  - {name: 美国, <<: *use, filter: "(?i)美|us|unitedstates|united states", type: select}

  - {name: 其它地区, <<: *use, filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*", type: select}

  - {name: 自动选择, <<: *use, tolerance: 100, type: url-test, lazy: true}

rules:
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,google,默认
  - GEOSITE,youtube,默认
  - GEOSITE,telegram,默认
  - GEOSITE,github,默认
  - GEOSITE,twitter,默认
  - GEOSITE,ehentai,默认
  - GEOSITE,netflix,默认
  - GEOSITE,spotify,默认
  - GEOSITE,bahamut,台湾
  - GEOSITE,geolocation-!cn,默认
  - GEOSITE,bilibili,DIRECT

  - GEOIP,google,默认
  - GEOIP,netflix,默认
  - GEOIP,telegram,默认
  - GEOIP,twitter,默认
  - GEOIP,private,DIRECT,no-resolve
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,默认
